model_checkpoint: "/content/drive/MyDrive/banking-intent-unsloth/checkpoints/final_best_model"
max_seq_length: 128
label_mapping_path: "/content/drive/MyDrive/banking-intent-unsloth/sample_data/label_mapping.json"
test_data_path: "/content/drive/MyDrive/banking-intent-unsloth/sample_data/test.csv"
output_dir: "results"
